name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch:
              - arm64
              - x86_64
            platform: apple-macos
          - os: ubuntu-24.04
            arch:
              - aarch64
              - x86_64
            platform: unknown-linux-gnu
    name: Publish ${{ matrix.os }} binaries to release
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          for arch in ${{ join(matrix.arch, ' ') }}; do
            swift build -c release --arch $arch
            mv .build/release/figma-export figma-export-$arch-${{ matrix.platform }}
          done

      - name: "Upload assets to a release"
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            figma-export-*-${{ matrix.platform }}